<?php

namespace Database\Seeders;

use App\Models\Localidad;
use App\Models\Provincia;
use Illuminate\Database\Seeder;

class LocalidadNorteSeeder extends Seeder
{
    public function run(): void
    {
        $localidades = [
            ['nombre' => 'San Fernando del Valle de Catamarca', 'provincia' => 'Catamarca'],
            ['nombre' => 'Andalgalá', 'provincia' => 'Catamarca'],
            ['nombre' => 'Antofagasta de la Sierra', 'provincia' => 'Catamarca'],
            ['nombre' => 'Belén', 'provincia' => 'Catamarca'],
            ['nombre' => 'Capayán', 'provincia' => 'Catamarca'],
            ['nombre' => 'El Alto', 'provincia' => 'Catamarca'],
            ['nombre' => 'Fiambalá', 'provincia' => 'Catamarca'],
            ['nombre' => 'Huillapima', 'provincia' => 'Catamarca'],
            ['nombre' => 'La Paz', 'provincia' => 'Catamarca'],
            ['nombre' => 'Londres', 'provincia' => 'Catamarca'],
            ['nombre' => 'Los Altos', 'provincia' => 'Catamarca'],
            ['nombre' => 'Mutquín', 'provincia' => 'Catamarca'],
            ['nombre' => 'Pomán', 'provincia' => 'Catamarca'],
            ['nombre' => 'Recreo', 'provincia' => 'Catamarca'],
            ['nombre' => 'San José', 'provincia' => 'Catamarca'],
            ['nombre' => 'Santa María', 'provincia' => 'Catamarca'],
            ['nombre' => 'Santa Rosa', 'provincia' => 'Catamarca'],
            ['nombre' => 'Saujil', 'provincia' => 'Catamarca'],
            ['nombre' => 'Tinogasta', 'provincia' => 'Catamarca'],
            ['nombre' => 'Valle Viejo', 'provincia' => 'Catamarca'],
            ['nombre' => 'Villa de Sumampa', 'provincia' => 'Catamarca'],
            ['nombre' => 'Villa Vil', 'provincia' => 'Catamarca'],
            ['nombre' => 'Aconquija', 'provincia' => 'Catamarca'],
            ['nombre' => 'Albigasta', 'provincia' => 'Catamarca'],
            ['nombre' => 'Alto de las Juntas', 'provincia' => 'Catamarca'],
            ['nombre' => 'Chumbicha', 'provincia' => 'Catamarca'],
            ['nombre' => 'El Rodeo', 'provincia' => 'Catamarca'],
            ['nombre' => 'Icaño', 'provincia' => 'Catamarca'],
            ['nombre' => 'Las Juntas', 'provincia' => 'Catamarca'],
            ['nombre' => 'Los Varela', 'provincia' => 'Catamarca'],
            ['nombre' => 'Medanitos', 'provincia' => 'Catamarca'],
            ['nombre' => 'Puerta de Corral Quemado', 'provincia' => 'Catamarca'],
            ['nombre' => 'Punta de Balasto', 'provincia' => 'Catamarca'],
            ['nombre' => 'San Antonio', 'provincia' => 'Catamarca'],
            ['nombre' => 'San Fernando', 'provincia' => 'Catamarca'],
            ['nombre' => 'Siján', 'provincia' => 'Catamarca'],
            ['nombre' => 'Tatón', 'provincia' => 'Catamarca'],
            ['nombre' => 'San Salvador de Jujuy', 'provincia' => 'Jujuy'],
            ['nombre' => 'Palpalá', 'provincia' => 'Jujuy'],
            ['nombre' => 'San Pedro de Jujuy', 'provincia' => 'Jujuy'],
            ['nombre' => 'Libertador General San Martín', 'provincia' => 'Jujuy'],
            ['nombre' => 'Humahuaca', 'provincia' => 'Jujuy'],
            ['nombre' => 'Tilcara', 'provincia' => 'Jujuy'],
            ['nombre' => 'Purmamarca', 'provincia' => 'Jujuy'],
            ['nombre' => 'Abra Pampa', 'provincia' => 'Jujuy'],
            ['nombre' => 'La Quiaca', 'provincia' => 'Jujuy'],
            ['nombre' => 'Yavi', 'provincia' => 'Jujuy'],
            ['nombre' => 'Susques', 'provincia' => 'Jujuy'],
            ['nombre' => 'El Aguilar', 'provincia' => 'Jujuy'],
            ['nombre' => 'Caimancito', 'provincia' => 'Jujuy'],
            ['nombre' => 'Calilegua', 'provincia' => 'Jujuy'],
            ['nombre' => 'Fraile Pintado', 'provincia' => 'Jujuy'],
            ['nombre' => 'Ledesma', 'provincia' => 'Jujuy'],
            ['nombre' => 'Monterrico', 'provincia' => 'Jujuy'],
            ['nombre' => 'Perico', 'provincia' => 'Jujuy'],
            ['nombre' => 'El Carmen', 'provincia' => 'Jujuy'],
            ['nombre' => 'Güemes', 'provincia' => 'Jujuy'],
            ['nombre' => 'Volcán', 'provincia' => 'Jujuy'],
            ['nombre' => 'Tumbaya', 'provincia' => 'Jujuy'],
            ['nombre' => 'Maimará', 'provincia' => 'Jujuy'],
            ['nombre' => 'Uquía', 'provincia' => 'Jujuy'],
            ['nombre' => 'Iturbe', 'provincia' => 'Jujuy'],
            ['nombre' => 'Tres Cruces', 'provincia' => 'Jujuy'],
            ['nombre' => 'Casabindo', 'provincia' => 'Jujuy'],
            ['nombre' => 'Cochinoca', 'provincia' => 'Jujuy'],
            ['nombre' => 'Rinconada', 'provincia' => 'Jujuy'],
            ['nombre' => 'Santa Catalina', 'provincia' => 'Jujuy'],
            ['nombre' => 'Hipólito Yrigoyen', 'provincia' => 'Jujuy'],
            ['nombre' => 'Orán', 'provincia' => 'Jujuy'],
            ['nombre' => 'Pichanal', 'provincia' => 'Jujuy'],
            ['nombre' => 'Embarcación', 'provincia' => 'Jujuy'],
            ['nombre' => 'Salta', 'provincia' => 'Salta'],
            ['nombre' => 'San Ramón de la Nueva Orán', 'provincia' => 'Salta'],
            ['nombre' => 'Tartagal', 'provincia' => 'Salta'],
            ['nombre' => 'General Güemes', 'provincia' => 'Salta'],
            ['nombre' => 'Cafayate', 'provincia' => 'Salta'],
            ['nombre' => 'Rosario de la Frontera', 'provincia' => 'Salta'],
            ['nombre' => 'Metán', 'provincia' => 'Salta'],
            ['nombre' => 'Joaquín V. González', 'provincia' => 'Salta'],
            ['nombre' => 'Embarcación', 'provincia' => 'Salta'],
            ['nombre' => 'Aguaray', 'provincia' => 'Salta'],
            ['nombre' => 'Salvador Mazza', 'provincia' => 'Salta'],
            ['nombre' => 'Profesor Salvador Mazza', 'provincia' => 'Salta'],
            ['nombre' => 'Cachi', 'provincia' => 'Salta'],
            ['nombre' => 'Chicoana', 'provincia' => 'Salta'],
            ['nombre' => 'La Caldera', 'provincia' => 'Salta'],
            ['nombre' => 'La Viña', 'provincia' => 'Salta'],
            ['nombre' => 'Molinos', 'provincia' => 'Salta'],
            ['nombre' => 'Payogasta', 'provincia' => 'Salta'],
            ['nombre' => 'Rosario de Lerma', 'provincia' => 'Salta'],
            ['nombre' => 'San Carlos', 'provincia' => 'Salta'],
            ['nombre' => 'Animaná', 'provincia' => 'Salta'],
            ['nombre' => 'El Carril', 'provincia' => 'Salta'],
            ['nombre' => 'El Galpón', 'provincia' => 'Salta'],
            ['nombre' => 'General Mosconi', 'provincia' => 'Salta'],
            ['nombre' => 'Hipólito Yrigoyen', 'provincia' => 'Salta'],
            ['nombre' => 'Pichanal', 'provincia' => 'Salta'],
            ['nombre' => 'Rivadavia', 'provincia' => 'Salta'],
            ['nombre' => 'Urundel', 'provincia' => 'Salta'],
            ['nombre' => 'Coronel Juan Solá', 'provincia' => 'Salta'],
            ['nombre' => 'Angastaco', 'provincia' => 'Salta'],
            ['nombre' => 'Isonza', 'provincia' => 'Salta'],
            ['nombre' => 'Nazareno', 'provincia' => 'Salta'],
            ['nombre' => 'Santa Victoria Este', 'provincia' => 'Salta'],
            ['nombre' => 'Iruya', 'provincia' => 'Salta'],
            ['nombre' => 'Los Toldos', 'provincia' => 'Salta'],
            ['nombre' => 'Colonia Santa Rosa', 'provincia' => 'Salta'],
            ['nombre' => 'Apolinario Saravia', 'provincia' => 'Salta'],
            ['nombre' => 'San Miguel de Tucumán', 'provincia' => 'Tucumán'],
            ['nombre' => 'Banda del Río Salí', 'provincia' => 'Tucumán'],
            ['nombre' => 'Yerba Buena', 'provincia' => 'Tucumán'],
            ['nombre' => 'Tafí Viejo', 'provincia' => 'Tucumán'],
            ['nombre' => 'Concepción', 'provincia' => 'Tucumán'],
            ['nombre' => 'Aguilares', 'provincia' => 'Tucumán'],
            ['nombre' => 'Alderetes', 'provincia' => 'Tucumán'],
            ['nombre' => 'Famailla', 'provincia' => 'Tucumán'],
            ['nombre' => 'Frías', 'provincia' => 'Tucumán'],
            ['nombre' => 'Juan Bautista Alberdi', 'provincia' => 'Tucumán'],
            ['nombre' => 'La Cocha', 'provincia' => 'Tucumán'],
            ['nombre' => 'Monteros', 'provincia' => 'Tucumán'],
            ['nombre' => 'Simoca', 'provincia' => 'Tucumán'],
            ['nombre' => 'Tafí del Valle', 'provincia' => 'Tucumán'],
            ['nombre' => 'Trancas', 'provincia' => 'Tucumán'],
            ['nombre' => 'Ranchillos', 'provincia' => 'Tucumán'],
            ['nombre' => 'Las Talitas', 'provincia' => 'Tucumán'],
            ['nombre' => 'El Manantial', 'provincia' => 'Tucumán'],
            ['nombre' => 'Lules', 'provincia' => 'Tucumán'],
            ['nombre' => 'Bella Vista', 'provincia' => 'Tucumán'],
            ['nombre' => 'Graneros', 'provincia' => 'Tucumán'],
            ['nombre' => 'Burruyacu', 'provincia' => 'Tucumán'],
            ['nombre' => 'Chicligasta', 'provincia' => 'Tucumán'],
            ['nombre' => 'Cruz Alta', 'provincia' => 'Tucumán'],
            ['nombre' => 'Leales', 'provincia' => 'Tucumán'],
            ['nombre' => 'Río Chico', 'provincia' => 'Tucumán'],
            ['nombre' => 'Los Ralos', 'provincia' => 'Tucumán'],
            ['nombre' => 'Villa Benjamín Araoz', 'provincia' => 'Tucumán'],
            ['nombre' => 'Acheral', 'provincia' => 'Tucumán'],
            ['nombre' => 'Capitán Cáceres', 'provincia' => 'Tucumán'],
            ['nombre' => 'El Cercado', 'provincia' => 'Tucumán'],
            ['nombre' => 'El Mollar', 'provincia' => 'Tucumán'],
            ['nombre' => 'Los Nogales', 'provincia' => 'Tucumán'],
            ['nombre' => 'Quilmes', 'provincia' => 'Tucumán'],
            ['nombre' => 'Santa Ana', 'provincia' => 'Tucumán'],
            ['nombre' => 'Vipos', 'provincia' => 'Tucumán'],
            ['nombre' => 'La Rioja', 'provincia' => 'La Rioja'],
            ['nombre' => 'Chilecito', 'provincia' => 'La Rioja'],
            ['nombre' => 'Arauco', 'provincia' => 'La Rioja'],
            ['nombre' => 'Chamical', 'provincia' => 'La Rioja'],
            ['nombre' => 'Chepes', 'provincia' => 'La Rioja'],
            ['nombre' => 'Patquía', 'provincia' => 'La Rioja'],
            ['nombre' => 'Aimogasta', 'provincia' => 'La Rioja'],
            ['nombre' => 'Castro Barros', 'provincia' => 'La Rioja'],
            ['nombre' => 'Famatina', 'provincia' => 'La Rioja'],
            ['nombre' => 'General Ángel Vicente Peñaloza', 'provincia' => 'La Rioja'],
            ['nombre' => 'General Belgrano', 'provincia' => 'La Rioja'],
            ['nombre' => 'General Felipe Varela', 'provincia' => 'La Rioja'],
            ['nombre' => 'General Juan Facundo Quiroga', 'provincia' => 'La Rioja'],
            ['nombre' => 'General Lamadrid', 'provincia' => 'La Rioja'],
            ['nombre' => 'General Ortiz de Ocampo', 'provincia' => 'La Rioja'],
            ['nombre' => 'General Sán Martín', 'provincia' => 'La Rioja'],
            ['nombre' => 'Independencia', 'provincia' => 'La Rioja'],
            ['nombre' => 'Vinchina', 'provincia' => 'La Rioja'],
            ['nombre' => 'Coronel Felipe Varela', 'provincia' => 'La Rioja'],
            ['nombre' => 'Nonogasta', 'provincia' => 'La Rioja'],
            ['nombre' => 'San Blas de los Sauces', 'provincia' => 'La Rioja'],
            ['nombre' => 'Shincal', 'provincia' => 'La Rioja'],
            ['nombre' => 'Villa Castelli', 'provincia' => 'La Rioja'],
            ['nombre' => 'Villa Sanagasta', 'provincia' => 'La Rioja'],
            ['nombre' => 'Villa Unión', 'provincia' => 'La Rioja'],
            ['nombre' => 'Santiago del Estero', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'La Banda', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Termas de Río Hondo', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Añatuya', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Frías', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Loreto', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Monte Quemado', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Nueva Esperanza', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Quimilí', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Suncho Corral', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Villa Ojo de Agua', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Bandera', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Clodomira', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Colonia Dora', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'El Hoyo', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Fernández', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Forres', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Garza', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Huyamampa', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Juan Felipe Ibarra', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Jumeal', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Laprida', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Los Juries', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Los Núñez', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Los Telares', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Maco', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Mailín', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Mansilla', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Mitre', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Otumpa', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Pampa de los Guanacos', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Pinto', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Pozo Hondo', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Real Sayana', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Sachayoj', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'San Pedro de Guasayán', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Selva', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Tintina', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Weisburd', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Averías', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Choya', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Colonia El Simbolar', 'provincia' => 'Santiago del Estero'],
            ['nombre' => 'Resistencia', 'provincia' => 'Chaco'],
            ['nombre' => 'Presidencia Roque Sáenz Peña', 'provincia' => 'Chaco'],
            ['nombre' => 'Villa Ángela', 'provincia' => 'Chaco'],
            ['nombre' => 'Charata', 'provincia' => 'Chaco'],
            ['nombre' => 'General San Martín', 'provincia' => 'Chaco'],
            ['nombre' => 'Las Breñas', 'provincia' => 'Chaco'],
            ['nombre' => 'Quitilipi', 'provincia' => 'Chaco'],
            ['nombre' => 'Presidencia de la Plaza', 'provincia' => 'Chaco'],
            ['nombre' => 'Makallé', 'provincia' => 'Chaco'],
            ['nombre' => 'Fontana', 'provincia' => 'Chaco'],
            ['nombre' => 'Barranqueras', 'provincia' => 'Chaco'],
            ['nombre' => 'Puerto Tirol', 'provincia' => 'Chaco'],
            ['nombre' => 'Colonia Benítez', 'provincia' => 'Chaco'],
            ['nombre' => 'El Zapallar', 'provincia' => 'Chaco'],
            ['nombre' => 'Gancedo', 'provincia' => 'Chaco'],
            ['nombre' => 'General Donovan', 'provincia' => 'Chaco'],
            ['nombre' => 'General Pinedo', 'provincia' => 'Chaco'],
            ['nombre' => 'Juan José Castelli', 'provincia' => 'Chaco'],
            ['nombre' => 'La Eduvigis', 'provincia' => 'Chaco'],
            ['nombre' => 'Laguna Blanca', 'provincia' => 'Chaco'],
            ['nombre' => 'Los Frentones', 'provincia' => 'Chaco'],
            ['nombre' => 'Machagai', 'provincia' => 'Chaco'],
            ['nombre' => 'Miraflores', 'provincia' => 'Chaco'],
            ['nombre' => 'Napalpi', 'provincia' => 'Chaco'],
            ['nombre' => 'Pampa del Infierno', 'provincia' => 'Chaco'],
            ['nombre' => 'Pampa Almirón', 'provincia' => 'Chaco'],
            ['nombre' => 'Pampa del Indio', 'provincia' => 'Chaco'],
            ['nombre' => 'Presidencia Roca', 'provincia' => 'Chaco'],
            ['nombre' => 'Puerto Bermejo', 'provincia' => 'Chaco'],
            ['nombre' => 'Puerto Eva Perón', 'provincia' => 'Chaco'],
            ['nombre' => 'Puerto Vilelas', 'provincia' => 'Chaco'],
            ['nombre' => 'Samuhú', 'provincia' => 'Chaco'],
            ['nombre' => 'San Bernardo', 'provincia' => 'Chaco'],
            ['nombre' => 'Santa Sylvina', 'provincia' => 'Chaco'],
            ['nombre' => 'Taco Pozo', 'provincia' => 'Chaco'],
            ['nombre' => 'Tres Isletas', 'provincia' => 'Chaco'],
            ['nombre' => 'Villa Berthet', 'provincia' => 'Chaco'],
            ['nombre' => 'Formosa', 'provincia' => 'Formosa'],
            ['nombre' => 'Clorinda', 'provincia' => 'Formosa'],
            ['nombre' => 'El Colorado', 'provincia' => 'Formosa'],
            ['nombre' => 'Ingeniero Juárez', 'provincia' => 'Formosa'],
            ['nombre' => 'Las Lomitas', 'provincia' => 'Formosa'],
            ['nombre' => 'Pirané', 'provincia' => 'Formosa'],
            ['nombre' => 'General Enrique Mosconi', 'provincia' => 'Formosa'],
            ['nombre' => 'Comandante Fontana', 'provincia' => 'Formosa'],
            ['nombre' => 'Estanislao del Campo', 'provincia' => 'Formosa'],
            ['nombre' => 'General Lucio Victorio Mansilla', 'provincia' => 'Formosa'],
            ['nombre' => 'Gran Guardia', 'provincia' => 'Formosa'],
            ['nombre' => 'Ibarreta', 'provincia' => 'Formosa'],
            ['nombre' => 'Laguna Blanca', 'provincia' => 'Formosa'],
            ['nombre' => 'Laguna Yema', 'provincia' => 'Formosa'],
            ['nombre' => 'Los Chiriguanos', 'provincia' => 'Formosa'],
            ['nombre' => 'Misión Laishi', 'provincia' => 'Formosa'],
            ['nombre' => 'Misión Tacaaglé', 'provincia' => 'Formosa'],
            ['nombre' => 'Palo Santo', 'provincia' => 'Formosa'],
            ['nombre' => 'Pozo del Tigre', 'provincia' => 'Formosa'],
            ['nombre' => 'Riacho He-Hé', 'provincia' => 'Formosa'],
            ['nombre' => 'San Francisco de Laishí', 'provincia' => 'Formosa'],
            ['nombre' => 'Subteniente Perín', 'provincia' => 'Formosa'],
            ['nombre' => 'Villa Dos Trece', 'provincia' => 'Formosa'],
            ['nombre' => 'Villa General Güemes', 'provincia' => 'Formosa'],
            ['nombre' => 'Posadas', 'provincia' => 'Misiones'],
            ['nombre' => 'Oberá', 'provincia' => 'Misiones'],
            ['nombre' => 'Eldorado', 'provincia' => 'Misiones'],
            ['nombre' => 'Puerto Iguazú', 'provincia' => 'Misiones'],
            ['nombre' => 'Apóstoles', 'provincia' => 'Misiones'],
            ['nombre' => 'Aristóbulo del Valle', 'provincia' => 'Misiones'],
            ['nombre' => 'Bernardo de Irigoyen', 'provincia' => 'Misiones'],
            ['nombre' => 'Candelaria', 'provincia' => 'Misiones'],
            ['nombre' => 'Capioví', 'provincia' => 'Misiones'],
            ['nombre' => 'Cerro Azul', 'provincia' => 'Misiones'],
            ['nombre' => 'Colonia Aurora', 'provincia' => 'Misiones'],
            ['nombre' => 'Colonia Delicia', 'provincia' => 'Misiones'],
            ['nombre' => 'Concepción de la Sierra', 'provincia' => 'Misiones'],
            ['nombre' => 'Corpus', 'provincia' => 'Misiones'],
            ['nombre' => 'El Doradillo', 'provincia' => 'Misiones'],
            ['nombre' => 'Esperanza', 'provincia' => 'Misiones'],
            ['nombre' => 'Garuhapé', 'provincia' => 'Misiones'],
            ['nombre' => 'General Alvear', 'provincia' => 'Misiones'],
            ['nombre' => 'Hipólito Yrigoyen', 'provincia' => 'Misiones'],
            ['nombre' => 'Jardín América', 'provincia' => 'Misiones'],
            ['nombre' => 'Leandro N. Alem', 'provincia' => 'Misiones'],
            ['nombre' => 'Los Helechos', 'provincia' => 'Misiones'],
            ['nombre' => 'Montecarlo', 'provincia' => 'Misiones'],
            ['nombre' => 'Panambí', 'provincia' => 'Misiones'],
            ['nombre' => 'Picada Libertad', 'provincia' => 'Misiones'],
            ['nombre' => 'Profundidad', 'provincia' => 'Misiones'],
            ['nombre' => 'Puerto Libertad', 'provincia' => 'Misiones'],
            ['nombre' => 'Puerto Piray', 'provincia' => 'Misiones'],
            ['nombre' => 'Puerto Rico', 'provincia' => 'Misiones'],
            ['nombre' => 'Ruiz de Montoya', 'provincia' => 'Misiones'],
            ['nombre' => 'San Antonio', 'provincia' => 'Misiones'],
            ['nombre' => 'San Ignacio', 'provincia' => 'Misiones'],
            ['nombre' => 'San Javier', 'provincia' => 'Misiones'],
            ['nombre' => 'San Pedro', 'provincia' => 'Misiones'],
            ['nombre' => 'San Vicente', 'provincia' => 'Misiones'],
            ['nombre' => 'Santo Pipó', 'provincia' => 'Misiones'],
            ['nombre' => 'Wanda', 'provincia' => 'Misiones'],
            ['nombre' => 'Corrientes', 'provincia' => 'Corrientes'],
            ['nombre' => 'Goya', 'provincia' => 'Corrientes'],
            ['nombre' => 'Paso de los Libres', 'provincia' => 'Corrientes'],
            ['nombre' => 'Curuzú Cuatiá', 'provincia' => 'Corrientes'],
            ['nombre' => 'Mercedes', 'provincia' => 'Corrientes'],
            ['nombre' => 'Bella Vista', 'provincia' => 'Corrientes'],
            ['nombre' => 'Santo Tomé', 'provincia' => 'Corrientes'],
            ['nombre' => 'Esquina', 'provincia' => 'Corrientes'],
            ['nombre' => 'Saladas', 'provincia' => 'Corrientes'],
            ['nombre' => 'Mburucuyá', 'provincia' => 'Corrientes'],
            ['nombre' => 'San Luis del Palmar', 'provincia' => 'Corrientes'],
            ['nombre' => 'Caá Catí', 'provincia' => 'Corrientes'],
            ['nombre' => 'General Paz', 'provincia' => 'Corrientes'],
            ['nombre' => 'Ituzaingó', 'provincia' => 'Corrientes'],
            ['nombre' => 'Itatí', 'provincia' => 'Corrientes'],
            ['nombre' => 'La Cruz', 'provincia' => 'Corrientes'],
            ['nombre' => 'Lavalle', 'provincia' => 'Corrientes'],
            ['nombre' => 'Loreto', 'provincia' => 'Corrientes'],
            ['nombre' => 'Mocoretá', 'provincia' => 'Corrientes'],
            ['nombre' => 'Monte Caseros', 'provincia' => 'Corrientes'],
            ['nombre' => 'Perugorría', 'provincia' => 'Corrientes'],
            ['nombre' => 'Sauce', 'provincia' => 'Corrientes'],
            ['nombre' => 'San Cosme', 'provincia' => 'Corrientes'],
            ['nombre' => 'San Miguel', 'provincia' => 'Corrientes'],
            ['nombre' => 'San Roque', 'provincia' => 'Corrientes'],
            ['nombre' => 'Santa Lucía', 'provincia' => 'Corrientes'],
            ['nombre' => 'Tabay', 'provincia' => 'Corrientes'],
            ['nombre' => 'Tatacuá', 'provincia' => 'Corrientes'],
            ['nombre' => 'Virasoro', 'provincia' => 'Corrientes'],
        ];

        foreach ($localidades as $item) {
            $provincia = Provincia::where('nombre', $item['provincia'])->first();
            if ($provincia) {
                Localidad::firstOrCreate([
                    'nombre' => $item['nombre'],
                    'provincia_id' => $provincia->id,
                ]);
            }
        }
    }
}
